name: toolkit
description: ToolKitX is the latest end-to-end Software as a Service (SaaS) solution for field workforce management. We drive our customer's success by simplifying, automating and digitalizing their environment.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  intl:
  get_it:
  shimmer:
  encrypt:
  equatable:
  open_filex:
  flutter_svg:
  flutter_bloc:
  hive_flutter:
  url_launcher:
  image_picker:
  path_provider:
  toggle_switch:
  json_annotation: 4.8.1
  cupertino_icons: ^1.0.2
  package_info_plus: ^4.0.2
  connectivity_plus:
  shared_preferences:
  permission_handler:
  searchable_listview: ^2.4.0
  cached_network_image:
  signature: ^5.4.0
  flutter_inappwebview: ^5.7.2+3
  image_cropper: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
  json_serializable:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
