name: toolkit
description: ToolKitX is the latest end-to-end Software as a Service (SaaS) solution for field workforce management. We drive our customer's success by simplifying, automating and digitalizing their environment.
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  intl:
  get_it:
  equatable:
  open_filex:
  flutter_svg:
  flutter_bloc:
  hive_flutter:
  url_launcher:
  image_picker:
  path_provider:
  json_annotation:
  cupertino_icons: ^1.0.2
  connectivity_plus:
  shared_preferences:
  permission_handler:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/
